### PR TITLE
Added JSON.MERGE to lettucemod

### PR DESCRIPTION
**Pull request by lpawlak1**
Provided way to interact with Json.Merge of RedisJSON 2.6.0 :)

### CODE REVIEW

**Comment by lpawlak1** [comment]
@jruaux
Please review this PR.

I would like to add this feature as soon as possible as its needed for bachelor thesis of mine :))

**Comment by jruaux** [comment]
@lpawlak1  Thanks for your contribution. Unfortunately the tests (and many others in the lettucemod test suite) are not passing. I think this is due to the latest RediSearch release but I cannot find the root cause... If you have any idea please chime in

**Comment by jruaux** [comment]
I think the issue is fixed now. Can you merge your PR and I'll run the tests again

**Comment by lpawlak1** [comment]
@jruaux Everything looks good now

**Comment by jruaux** [comment]
Your contribution was included in 3.7.0. Thanks again!

**Pull request merged**
